### PR TITLE
display errors on submit fail, rethrow when not a submission error

### PR DESCRIPTION
**Pull request by wwelling**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
Looks good! And _very_ welcome.

Only point of style: instead of a blanket `eslint-disable-line`, we prefer the specific `eslint-disable-line name-of-specific-error`.

**Comment by skomorokh** [comment]
I would change the order in the `Object.assign()` so that opts is at the end. That way consumers of the wrapper can still choose to provide their own `onSubmitFail` to override this default one, otherwise it kinda breaks attempts at handling validation... ?

**Comment by wwelling** [comment]
@skomorokh validation handling works as was before. 

@MikeTaylor I will update the lint ignore with specific rule

**Comment by MikeTaylor** [comment]
Looks great! I am _so_ looking forward to seeing error messages!

**Pull request merged**
