### PR TITLE
Stripes 467 scrolltoerror

### PR DESCRIPTION
**Pull request by aditya-matukumalli**

### CODE REVIEW

**Comment by aditya-matukumalli** [comment]
@jeremythuff They should be gone now.

**Comment by jeremythuff** [comment]
This looks straight forward. I was a bit surprised to see the call to document.querySelector, as I feel that we rarely interact with elements directly but instead get at the elements via their components, but I cannot see why that would be a problem in this instance.

**Comment by aditya-matukumalli** [comment]
@jeremythuff  We use the document.querySelector so we could grab the erroneous input field directly from the DOM by their names from the errors object, or an alternative approach is to add refs to each and every input field on all of the forms to grab them when an error occurs which I guess is a lot of rework and maybe too much effort for just scrolling to a validation error.

**Comment by aditya-matukumalli** [comment]
@jeremythuff  Yeah, that makes sense. There is no point in scrolling to an error when the form is not long enough. I will add that in.

**Comment by aditya-matukumalli** [comment]
Added the logic so that the form scrolls only when scrollToError: true is passed into the redux form. If this looks good, I will go ahead and add the opt parameter to the forms which are long enough and might need scrolling on error, Eg: UserForm

**Comment by jeremythuff** [comment]
Looks great!

**Pull request merged**
