### PR TITLE
STFORM-9 Scroll form to Display Validation Errors that are react elements

### PR DESCRIPTION
**Pull request by NikitaSedyx**
https://issues.folio.org/browse/STFORM-9

problem:
core component doesn't support translated error messages

approach:
detect `$$typeof` property and add its parent property to the errors list

### CODE REVIEW

**Comment by doytch** [comment]
So, it's difficult for me to tell _exactly_ what's being checked here without stepping into the debugger so I'm not sure, but would it be possible to use [`isValidElement`](https://reactjs.org/docs/react-api.html#isvalidelement) rather than the `$$typeof` check?

**Comment by NikitaSedyx** [comment]
@doytch actually `isValidElement` checks `$$typeof` and to use it we should have our own `flatten` version with support all cases that we already have, so I decided to do the easiest way to not create new bugs

**Comment by doytch** [comment]
@NikitaSedyx Hmm yeah, I see your point. There doesn't seem to be a nice and ideal solution here. That's too bad!

**Comment by NikitaSedyx** [comment]
@doytch I'm open for any suggestions :) otherwise someone can merge this one as I don't have permissions for this and we already have 3+ issues in different module that requires this fix

**Pull request merged**
